name = "slack-connect-bot"
main = "src/index.ts"
compatibility_date = "2025-06-27"
compatibility_flags = ["nodejs_compat"]

# Infisical関連の環境変数は wrangler secret で設定
# npx wrangler secret put INFISICAL_CLIENT_ID
# npx wrangler secret put INFISICAL_CLIENT_SECRET
# npx wrangler secret put INFISICAL_PROJECT_ID
# npx wrangler secret put INFISICAL_ENVIRONMENT

[[routes]]
pattern = "api.agiletec.net/*"
zone_name = "agiletec.net"

[[routes]]
pattern = "stg.agiletec.net/*"
zone_name = "agiletec.net"

# 環境ごとの設定は不要（Secretsで管理）