name = "slack-connect-bot"
main = "src/index.ts"
compatibility_date = "2025-06-27"

[vars]
INFISICAL_CLIENT_ID = "YOUR_INFISICAL_CLIENT_ID"
INFISICAL_CLIENT_SECRET = "YOUR_INFISICAL_CLIENT_SECRET"
INFISICAL_PROJECT_ID = "YOUR_PROJECT_ID"
INFISICAL_ENVIRONMENT = "prod"

[[routes]]
pattern = "api.agiletec.net/*"
zone_name = "agiletec.net"

[[routes]]
pattern = "stg.agiletec.net/*"
zone_name = "agiletec.net"

[env.production]
vars = { INFISICAL_ENVIRONMENT = "prod" }

[env.staging]
vars = { INFISICAL_ENVIRONMENT = "staging" }